# Generated by Django 4.1.7 on 2023-02-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_author_genre_alter_post_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
    ]
