# Generated by Django 4.1.7 on 2023-02-28 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_post_author_remove_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET,
                related_name="blog_author",
                to="post.author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET,
                related_name="blog_category",
                to="post.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET,
                related_name="author_genre",
                to="post.category",
            ),
        ),
    ]
