# Generated by Django 4.1.7 on 2023-02-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_author_name_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
